FROM erikj/ruby:2.2.0-for-rails
MAINTAINER Erik Johnson "erik@erikj.me"

# http://stackoverflow.com/questions/13702417/postgresql-gem-pg-was-unable-to-install

RUN yum install -y postgresql-libs postgresql-devel
